### ISSUE TITLE
Upgrade framework to Palladio 5.2

### ISSUE THREAD

**Issue by sebinside** [DataFlowAnalysis/DataFlowAnalysis#103]
The new version of Palladio has been published recently and we should update both our Eclipse version as the Palladio dependencies.

**Comment by Nicolas-Boltz** [comment]
It is done for the product. However, there was a lot of strange behavior. I suggest the following:
Currently, the PCM-Extension builds with the nightly of Palladio. We should fix it to version 5.2.0 and only switch it to nightly or a newer release if necessary. This ensures that we do not have any weird things happening when something in the Palladio nightly breaks. 
Previously this was not possible, due to java and eclipse version differences.
