### ISSUE TITLE
DFD Tests fail locally

### ISSUE THREAD

**Issue by uuqjz** [DataFlowAnalysis/DataFlowAnalysis#168]
The OnlineShopDFDTest and BaseTest fail locally in eclipse:

org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.emf.ecore.xmi.PackageNotFoundException: Package with uri 'http://dataflowanalysis.org/dfd/dataflowdiagram' not found. (platform:/plugin/org.dataflowanalysis.analysis.testmodels/models/OnlineShopDFD/onlineshop.dataflowdiagram, 2, 242)

FYI I am using the newest product

**Comment by Entenwilli** [comment]
This is due to the recent changes in https://github.com/DataFlowAnalysis/DataFlowAnalysis/pull/155. 
Please use the updated product from the [updatesite](https://updatesite.palladio-simulator.com/DataFlowAnalysis/product/nightly/). Alternatively, you can update the DFD-Metamodel Plugin to the latest version

**Comment by uuqjz** [comment]
Youre right, i am using the latest release, will tryout nightly now

**Comment by uuqjz** [comment]
Work with the nightly release
